### PR TITLE
minor adjustments

### PR DESCRIPTION
**Pull request by matrob**
I've made some minor adjustments. Now you can use unbound (1.9.2), which has a lot of bug fixes.
Constructive feedback from you is welcome.
Best regards

### CODE REVIEW

**Comment by thrynir** [comment]
Hi,

I'm agree to change google.com to mozilla.org.
For named.root/cache as the package add root.ints, I switch to it.
In the future, the layer "COPY root/ /" will be removed as well by modifying directly original unbound.conf

I checked and agree about unbound (1.9.2) bugs issues. But I won't use Alpine's Edge branch as they explicitly warn us to not use it on production environment.
As 3.10 stable have just been released, I only update to 3.10. Unbound will be upgraded to 1.9.1-r2

Regards,

**Comment by matrob** [comment]
Thank you very much for your constructive comments.
Maybe mozilla.org isn't the best choice either, but it's usable for now.

Maybe the following option is an alternative to using a more recent version of unbound?
`apk add unbound --repository=http://dl-cdn.alpinelinux.org/alpine/edge/main`

Best regards

**Comment by thrynir** [comment]
It's the same as using edge branch.

As I said, I won't.

Regards,

**Comment by matrob** [comment]
No problem. Stability is also very important to me for productive use.  I very much hope that the newer and error corrected version of unbound will soon be available in alpine stable repo.
Best regards

**Pull request closed without merging**
